server:
  port: 8080
management:
  port: 9090

info:
  env: ${spring.profiles.active}
  
logging:
  path: /opt/application/logs
  
endpoint:
  restart:
    enabled: true
  autoconfig:
    enabled: true
    
spring:
    boot:
      admin:
        url: http://tl-bootadmin11:8080
        period: 10000
        auto-deregistration: true
        client:
          name: ${spring.application.name}             
          
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://tl-bootreg11:8080/eureka/