server:
  port: 8888
      
spring:
  application:
    name: spring-boot-config-server
    description: Microservice Config Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/valchkou/config-repo