server:
  port: 8080

management:
  port: 9999

spring:
  application:
    name: Spring Boot Cloud Microservice
    title: Spring Boot Cloud Microservice
    description: Sample Spring Boot Microservice 
